---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: daniel-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module

modules:
  - type: dnf
    repos:
      copr:
        - yalter/niri
        - avengemedia/dms
    install:
      packages:
        # wayland and compositor
        - niri
        - qt5-wayland
        - qt6-wayland
        - xwayland-satellite

        # dankmaterialshell
        - dms
        - accountsservice
        - cava
        - matugen
        - qt6ct
        - qt6-qtmultimedia

        # system utilities
        - wl-clipboard
        - distrobox
        - alsa-firmware
        - polkit
        - dbus-tools
        - wireplumber
        - pulseaudio-utils

        # network and bluetooth
        - network-manager-applet
        - bluez
        - bluez-tools
        - blueman
        - NetworkManager-openvpn-gnome
        - NetworkManager-openconnect-gnome

        # file Management and media
        - nautilus
        - gvfs-mtp
        - gvfs-smb
        - ffmpeg
        - gnome-keyring
        - adw-gtk3-theme
        - xdg-desktop-portal-gnome

        # cli tools
        - micro
        - fish
        - eza
        - bat
        - kitty

  # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: files
    files:
      - source: basics
        destination: /

  - type: signing
